Member/raveena
Year-3-Assignments/school-api pull request #16
Opened 2021-07-28 09:44 UTC by RaveenaWickramasinghe

2021-07-28 09:51 UTC, rusiruavb requested changes
Please make necessary changes

2021-07-28 09:51 UTC, rusiruavb commented on src/controller/student.controller.js
> +            '_id firstname lastname dateofbirth address1 address2 city province grade imageurl achievements parent phone email username',
In enum
'STUDENT_SELECT': '_id firstname lastname dateofbirth address1 address2 city province grade imageurl achievements parent phone email username'

In controller
enums.student.STUDENT_SLECT

**Look question.controller.js file**

2021-07-29 07:46 UTC, RaveenaWickramasinghe reviewed
Changes done

2021-07-29 07:49 UTC, rusiruavb requested changes

2021-07-29 07:49 UTC, rusiruavb commented on src/controller/student.controller.js
> +        res.status(200).json(data);
Use response handler

2021-07-29 08:05 UTC, RaveenaWickramasinghe reviewed
Added response handlers to the student controller file

2021-08-02 17:26 UTC, rusiruavb approved these changes
LGTM

2021-08-02 17:26 UTC, merged